------Data Division /split-------------

**-- Machine Learning --------------**
- - Data= x(Input data)+y(target data)
- - x-----------> x_train,x_test
- - y---------->y_train,y_test

- - -for machine training we will pass (x_train,y_train)
- - - for machine testing (x_test) ----------y_pred

- - - ex.
   
   1+1=2

   1+2=3

   1+3=4

   1+5=6

   1+6=7


   x=(1+1,1+2................)

   y=(2,3,4,6,7)

   x_train=(1+1,1+2,1+3)

   x_test=(2,3,4)

   y_train=(1+5,1+6)

   y_test=(6,7)

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/covid_toy - covid_toy.csv')
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [ ]:
df.shape

(100, 6)

In [ ]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
df['fever']=df['fever'].fillna(df['fever'].mean())

In [ ]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [ ]:
x=df.drop(columns=['has_covid'])  #input data
x

    age  gender  fever   cough       city
0    60    Male  103.0    Mild    Kolkata
1    27    Male  100.0    Mild      Delhi
2    42    Male  101.0    Mild      Delhi
3    31  Female   98.0    Mild    Kolkata
4    65  Female  101.0    Mild     Mumbai
..  ...     ...    ...     ...        ...
95   12  Female  104.0    Mild  Bangalore
96   51  Female  101.0  Strong    Kolkata
97   20  Female  101.0    Mild  Bangalore
98    5  Female   98.0  Strong     Mumbai
99   10  Female   98.0  Strong    Kolkata

[100 rows x 5 columns]

In [ ]:
y=df['has_covid']     #traget or output data
y

0      No
1     Yes
2      No
3      No
4      No
     ...
95     No
96    Yes
97     No
98     No
99    Yes
Name: has_covid, Length: 100, dtype: object

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=23)  #test_size= kitne % data test keliye rkhna hai, random_state=> fix data as like seek

In [ ]:
print("Total data shsap:",df.shape)
print("--------------------------------")
print("input data shap:",x.shape)
print("x_train shape:",x_train.shape)
print("x_test shape:",x_test.shape)
print("------------------------------")
print("targe data shap:",y.shape)
print("y_train shape:",y_train.shape)
print("y_test shape:",y_test.shape)

Total data shsap: (100, 6)
--------------------------------
input data shap: (100, 5)
x_train shape: (80, 5)
x_test shape: (20, 5)
------------------------------
targe data shap: (100,)
y_train shape: (80,)
y_test shape: (20,)

-- -----------------------------------01/04/2026----------------------Normal Distribution------------------------

**-- ----------StandardScaler--------------**


from sklearn.preprocessing import StandardScaler

-- StandardScaler (from scikit-learn) is a tool that scales your data.

z=(x-μ)/σ

z=standard deviations

x = original value

μ (mean) = average

σ (standard deviation) = spread

👉 StandardScaler brings the data to a standard form,

 -- using mean=0 and std=1

👉 It improves the performance of machine learning models

👉 It is especially useful in distance-based algorithms

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
 df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [ ]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [ ]:
df['fever']=df['fever'].fillna(df['fever'].mean())

In [ ]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [ ]:
df.columns

Index(['age', 'gender', 'fever', 'cough', 'city', 'has_covid'], dtype='object')

In [ ]:
f=df.drop(columns=['city'])
f

    age  gender  fever   cough has_covid
0    60    Male  103.0    Mild        No
1    27    Male  100.0    Mild       Yes
2    42    Male  101.0    Mild        No
3    31  Female   98.0    Mild        No
4    65  Female  101.0    Mild        No
..  ...     ...    ...     ...       ...
95   12  Female  104.0    Mild        No
96   51  Female  101.0  Strong       Yes
97   20  Female  101.0    Mild        No
98    5  Female   98.0  Strong        No
99   10  Female   98.0  Strong       Yes

[100 rows x 5 columns]

In [ ]:
f['gender']=f['gender'].map({"Female":1,"Male":0})
f['cough']=f['cough'].map({'Mild':0,'Strong':1})
f['has_covid']=f['has_covid'].map({'Yes':1,'No':0})

In [ ]:
f.head()

   age  gender  fever  cough  has_covid
0   60       0  103.0      0          0
1   27       0  100.0      0          1
2   42       0  101.0      0          0
3   31       1   98.0      0          0
4   65       1  101.0      0          0

In [ ]:
x=f.drop(columns=['has_covid'])

y=f['has_covid']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=23)

In [ ]:
np.round(x_train.describe(),2)

         age  gender   fever  cough
count  80.00   80.00   80.00  80.00
mean   44.39    0.59  100.96   0.36
std    24.99    0.50    1.97   0.48
min     5.00    0.00   98.00   0.00
25%    20.00    0.00   99.00   0.00
50%    45.50    1.00  101.00   0.00
75%    68.25    1.00  102.25   1.00
max    84.00    1.00  104.00   1.00

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc=StandardScaler()

In [ ]:
x_train_sc=sc.fit_transform(x_train) # fit means learn the parameters and transfrom means apply on that

In [ ]:
x_train_new=pd.DataFrame(x_train_sc,columns=x_train.columns)
x_train_new

         age    gender     fever     cough
0  -1.143081  0.837931  1.039859 -0.754074
1  -1.143081 -1.193416  1.549455 -0.754074
2  -1.022280  0.837931 -0.488929  1.326130
3   0.830005  0.837931 -1.508121 -0.754074
4  -1.384683 -1.193416 -0.488929 -0.754074
..       ...       ...       ...       ...
75  1.554812 -1.193416  1.039859 -0.754074
76  0.628669  0.837931 -0.998525 -0.754074
77 -0.418274 -1.193416 -1.508121  1.326130
78  0.185732  0.837931  0.530263 -0.754074
79 -1.102814  0.837931  1.549455 -0.754074

[80 rows x 4 columns]

In [ ]:
np.round(x_train_new.describe(),2)

         age  gender  fever  cough
count  80.00   80.00  80.00  80.00
mean   -0.00   -0.00   0.00  -0.00
std     1.01    1.01   1.01   1.01
min    -1.59   -1.19  -1.51  -0.75
25%    -0.98   -1.19  -1.00  -0.75
50%     0.04    0.84   0.02  -0.75
75%     0.96    0.84   0.66   1.33
max     1.60    0.84   1.55   1.33

------------07/04/2026------------------

**-- --MinMaxScaler-----------------------**


**from sklearn.preprocessing import MinMaxScaler**

-- MinMaxScaler (from scikit-learn) is a tool that scales your data between 0 and 1.

-- 👉 When you want values in a fixed range


--  Normalization ----> Using MinMaxScaling --->
-- -- Data Min_Value = 0 , Max_Value = 1

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('/content/covid_toy - covid_toy.csv')
df.head(5)

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

# step-1 ::: Convert categorical data into Numerical data

In [ ]:
df['gender']=df['gender'].map({'Female':1,'Male':0})
df['cough']= df['cough'].map({'Mild':0,'Strong':1})
df['has_covid']=df['has_covid'].map({'Yes':1,'No':0})

In [ ]:
df.head()

   age  gender  fever  cough     city  has_covid
0   60       0  103.0      0  Kolkata          0
1   27       0  100.0      0    Delhi          1
2   42       0  101.0      0    Delhi          0
3   31       1   98.0      0  Kolkata          0
4   65       1  101.0      0   Mumbai          0

# step-2:::: Data Dividation

In [ ]:
x=df.drop(columns=['city','has_covid'])
y=df['has_covid']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=23)

In [ ]:
np.round(x_train.describe(),2)

         age  gender   fever  cough
count  80.00   80.00   72.00  80.00
mean   44.39    0.59  100.97   0.36
std    24.99    0.50    2.08   0.48
min     5.00    0.00   98.00   0.00
25%    20.00    0.00   99.00   0.00
50%    45.50    1.00  101.00   0.00
75%    68.25    1.00  103.00   1.00
max    84.00    1.00  104.00   1.00

# step-3::: Apply MinMaxScaling

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
mm=MinMaxScaler()

In [ ]:
x_train_mm=mm.fit_transform(x_train)

In [ ]:
x_train_new=pd.DataFrame(x_train_mm,columns=x_train.columns)

In [ ]:
np.round(x_train_new.describe(),2)

         age  gender  fever  cough
count  80.00   80.00  72.00  80.00
mean    0.50    0.59   0.50   0.36
std     0.32    0.50   0.35   0.48
min     0.00    0.00   0.00   0.00
25%     0.19    0.00   0.17   0.00
50%     0.51    1.00   0.50   0.00
75%     0.80    1.00   0.83   1.00
max     1.00    1.00   1.00   1.00

-- ---------08/-4/2026--------------------

**-- Encoding =>** Transfrom your categorical data into Numerical data.

- -  **1.LabelEncoder** =>categorical data --> numerical data

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('/content/covid_toy - covid_toy.csv')
df.head(5)

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
df=df.dropna()

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
lb=LabelEncoder()

In [ ]:
df['gender']=lb.fit_transform(df['gender'])
df['cough']=lb.fit_transform(df['cough'])
df['city']=lb.fit_transform(df['city'])
df['has_covid']=lb.fit_transform(df['has_covid'])

In [ ]:
df.head(5)

   age  gender  fever  cough  city  has_covid
0   60       1  103.0      0     2          0
1   27       1  100.0      0     1          1
2   42       1  101.0      0     1          0
3   31       0   98.0      0     2          0
4   65       0  101.0      0     3          0

In [ ]:
x=df.drop(columns=['has_covid'])
y=df['has_covid']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=23)

In [ ]:
# Apply standardization for converting my data into normal distribution

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc=StandardScaler()

In [ ]:
x_train_sc=sc.fit_transform(x_train)

In [ ]:
x_train_new=pd.DataFrame(x_train_sc,columns=x_train.columns)

In [ ]:
np.round(x_train_new.describe(),2)

         age  gender  fever  cough   city
count  72.00   72.00  72.00  72.00  72.00
mean    0.00    0.00  -0.00  -0.00  -0.00
std     1.01    1.01   1.01   1.01   1.01
min    -1.57   -0.80  -1.49  -0.82  -1.19
25%    -1.00   -0.80  -0.99  -0.82  -1.19
50%     0.15   -0.80   0.01  -0.82  -0.18
75%     0.89    1.25   1.02   1.22   0.83
max     1.63    1.25   1.52   1.22   1.84

practies:-

In [ ]:
df=pd.read_csv('/content/tips.csv')
df.head(5)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df=df.dropna()

In [ ]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [ ]:
df['sex']=lb.fit_transform(df['sex'])
df['smoker']=lb.fit_transform(df['smoker'])
df['day']=lb.fit_transform(df['day'])
df['time']=lb.fit_transform(df['time'])

In [ ]:
df.head(3)

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    2     0     2
1       10.34  1.66    1       0    2     0     3
2       21.01  3.50    1       0    2     0     3

In [ ]:
x=df.drop(columns=['total_bill'])
y=df['total_bill']

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=23)

In [ ]:
#apply normalization
from sklearn.preprocessing import MinMaxScaler

In [ ]:
mn=MinMaxScaler()

In [ ]:
x_train_mn=mn.fit_transform(x_train)

In [ ]:
x_train_new=pd.DataFrame(x_train_mn,columns=x_train.columns)

In [ ]:
np.round(x_train_new.describe(),2)

          tip     sex  smoker     day    time    size
count  195.00  195.00  195.00  195.00  195.00  195.00
mean     0.23    0.67    0.41    0.57    0.27    0.31
std      0.15    0.47    0.49    0.31    0.44    0.19
min      0.00    0.00    0.00    0.00    0.00    0.00
25%      0.11    0.00    0.00    0.33    0.00    0.20
50%      0.22    1.00    0.00    0.67    0.00    0.20
75%      0.28    1.00    1.00    0.67    1.00    0.40
max      1.00    1.00    1.00    1.00    1.00    1.00

-- ------------10/04/2026---------

-- **2. Ordinal Encoding:-**

- - Label Encoding --> column[sub1,sub2,....]--> encode

- Ordinal Encoding :-> column[sub1,sub2,.....] --> rre-Arrange --> encode

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('/content/covid_toy - covid_toy.csv')
df.head(5)

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
df=df.dropna()

In [ ]:
df=df.drop(columns=['city','age','fever'])
df.head(2)

  gender cough has_covid
0   Male  Mild        No
1   Male  Mild       Yes

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe=OrdinalEncoder(categories=[['Male','Female'],['Mild','Strong'],['No','Yes']])

In [ ]:
oe_ar=oe.fit_transform(df)

In [ ]:
new_df=pd.DataFrame(oe_ar,columns=df.columns)

In [ ]:
new_df

    gender  cough  has_covid
0      0.0    0.0        0.0
1      0.0    0.0        1.0
2      0.0    0.0        0.0
3      1.0    0.0        0.0
4      1.0    0.0        0.0
..     ...    ...        ...
85     1.0    0.0        0.0
86     1.0    1.0        1.0
87     1.0    0.0        0.0
88     1.0    1.0        0.0
89     1.0    1.0        1.0

[90 rows x 3 columns]

- - - Second way:---

In [ ]:
df=pd.read_csv('/content/covid_toy - covid_toy.csv')
df.head(5)

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
df=df.dropna()

In [ ]:
df=df.drop(columns=['age','fever','city'])
df.head(2)

  gender cough has_covid
0   Male  Mild        No
1   Male  Mild       Yes

In [ ]:
x=df.drop(columns=['has_covid'])
y=df['has_covid']

In [ ]:
df.head(2)

  gender cough has_covid
0   Male  Mild        No
1   Male  Mild       Yes

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe=OrdinalEncoder(categories=[['Male','Female'],['Mild','Strong']])

In [ ]:
oe_ar_in=oe.fit_transform(x)

In [ ]:
y.head(2)

0     No
1    Yes
Name: has_covid, dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
lb=LabelEncoder()

In [ ]:
y=lb.fit_transform(y)

In [ ]:
y

array([0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1])

- LabelEncoder--> when we have single column.we cannot set sub-category form.
- -ex. has_covid['Yes','No'] ---> [1,0]
- OrdinalEncoder--> when we have multiple column .we can set sub_category form.
- - ex. has_covid['Yes','No'] ---> [1,0]/[0,1]

- first approch:-
- - df--> categorical column ---> ordinal encoder ---> data transform
- Second approch:-
- - df---> x,y then
- - - x---> encode by ordinal encoder
- - - y---> encode by Label encoder

- - class parcties:-
- - - - tips data:-
 - - - - target culumn-> 'total_bill'
 - - - - numerical column--> remove
 - - - - categorical column ---> ordinalEncoder

In [ ]:
df=pd.read_csv('/content/tips.csv')
df.head(5)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df=df.dropna()

In [ ]:
df=df.drop(columns=['size','tip'])
df.head(2)

   total_bill     sex smoker  day    time
0       16.99  Female     No  Sun  Dinner
1       10.34    Male     No  Sun  Dinner

In [ ]:
x=df.drop(columns=['total_bill'])
y=df['total_bill']

In [ ]:
x.head(2)

      sex smoker  day    time
0  Female     No  Sun  Dinner
1    Male     No  Sun  Dinner

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe=OrdinalEncoder(categories=[['Male','Female'],['No','Yes'],['Thur','Fri','Sat','Sun'],['Dinner','Lunch']])

In [ ]:
oe_arr=oe.fit_transform(x)

In [ ]:
oe_arr_df=pd.DataFrame(oe_arr,columns=x.columns)

In [ ]:
oe_arr_df.head(5)

   sex  smoker  day  time
0  1.0     0.0  3.0   0.0
1  0.0     0.0  3.0   0.0
2  0.0     0.0  3.0   0.0
3  0.0     0.0  3.0   0.0
4  1.0     0.0  3.0   0.0

--10/04/2026---------------
- - **3.get_dummies:-**

- - - - - colymn---> has_covid['YEs','No'] -->when we apply get_dummies ---> 2 column create

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('/content/insurance - insurance.csv')
df.head(4)

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061

In [ ]:
a=pd.get_dummies(df,columns=['sex','smoker','region'])
a.head(5)

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,True,False,False,True,False,False,False,True
1,18,33.770,1,1725.55230,False,True,True,False,False,False,True,False
2,28,33.000,3,4449.46200,False,True,True,False,False,False,True,False
3,33,22.705,0,21984.47061,False,True,True,False,False,True,False,False
4,32,28.880,0,3866.85520,False,True,True,False,False,True,False,False

In [ ]:
a=a.astype(int)
a

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
0,19,27,0,16884,1,0,0,1,0,0,0,1
1,18,33,1,1725,0,1,1,0,0,0,1,0
2,28,33,3,4449,0,1,1,0,0,0,1,0
3,33,22,0,21984,0,1,1,0,0,1,0,0
4,32,28,0,3866,0,1,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1333,50,30,3,10600,0,1,1,0,0,1,0,0
1334,18,31,0,2205,1,0,1,0,1,0,0,0
1335,18,36,0,1629,1,0,1,0,0,0,1,0
1336,21,25,0,2007,1,0,1,0,0,0,0,1
1337,61,29,0,29141,1,0,0,1,0,1,0,0

- if i have multiple sub-category--> 1 column drop--> data multiconielity issue resolve

- - ex. 1 student --> 2 days exam --> exam paper---> exam clear--> but 3 days ----> question answer--->xxx

In [ ]:
b=pd.get_dummies(df,columns=['sex','smoker','region'],drop_first=True)
b.head(5)

,age,bmi,children,charges,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,False,True,False,False,True
1,18,33.770,1,1725.55230,True,False,False,True,False
2,28,33.000,3,4449.46200,True,False,False,True,False
3,33,22.705,0,21984.47061,True,False,True,False,False
4,32,28.880,0,3866.85520,True,False,True,False,False

In [ ]:
b=b.astype(int)
b

,age,bmi,children,charges,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27,0,16884,0,1,0,0,1
1,18,33,1,1725,1,0,0,1,0
2,28,33,3,4449,1,0,0,1,0
3,33,22,0,21984,1,0,1,0,0
4,32,28,0,3866,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...
1333,50,30,3,10600,1,0,1,0,0
1334,18,31,0,2205,0,0,0,0,0
1335,18,36,0,1629,0,0,0,1,0
1336,21,25,0,2007,0,0,0,0,1
1337,61,29,0,29141,0,1,1,0,0

- practies:-

In [ ]:
df=pd.read_csv('/content/covid_toy - covid_toy.csv')
df.head(5)

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
a=pd.get_dummies(df,columns=['gender','cough','has_covid','city'])
a.head(5)

,age,fever,gender_Female,gender_Male,cough_Mild,cough_Strong,has_covid_No,has_covid_Yes,city_Bangalore,city_Delhi,city_Kolkata,city_Mumbai
0,60,103.0,False,True,True,False,True,False,False,False,True,False
1,27,100.0,False,True,True,False,False,True,False,True,False,False
2,42,101.0,False,True,True,False,True,False,False,True,False,False
3,31,98.0,True,False,True,False,True,False,False,False,True,False
4,65,101.0,True,False,True,False,True,False,False,False,False,True

In [ ]:
a=a.dropna()

In [ ]:
a=a.astype(int)
a

,age,fever,gender_Female,gender_Male,cough_Mild,cough_Strong,has_covid_No,has_covid_Yes,city_Bangalore,city_Delhi,city_Kolkata,city_Mumbai
0,60,103,0,1,1,0,1,0,0,0,1,0
1,27,100,0,1,1,0,0,1,0,1,0,0
2,42,101,0,1,1,0,1,0,0,1,0,0
3,31,98,1,0,1,0,1,0,0,0,1,0
4,65,101,1,0,1,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
95,12,104,1,0,1,0,1,0,1,0,0,0
96,51,101,1,0,0,1,0,1,0,0,1,0
97,20,101,1,0,1,0,1,0,1,0,0,0
98,5,98,1,0,0,1,1,0,0,0,0,1
99,10,98,1,0,0,1,0,1,0,0,1,0

In [ ]:
b=pd.get_dummies(df,columns=['gender','cough','has_covid','city'],drop_first=True)
b.head(5)

,age,fever,gender_Male,cough_Strong,has_covid_Yes,city_Delhi,city_Kolkata,city_Mumbai
0,60,103.0,True,False,False,False,True,False
1,27,100.0,True,False,True,True,False,False
2,42,101.0,True,False,False,True,False,False
3,31,98.0,False,False,False,False,True,False
4,65,101.0,False,False,False,False,False,True

In [ ]:
b=b.dropna()

In [ ]:
b=b.astype(int)
b.head(5)

,age,fever,gender_Male,cough_Strong,has_covid_Yes,city_Delhi,city_Kolkata,city_Mumbai
0,60,103,1,0,0,0,1,0
1,27,100,1,0,1,1,0,0
2,42,101,1,0,0,1,0,0
3,31,98,0,0,0,0,1,0
4,65,101,0,0,0,0,0,1

- **4.OnehotEncoder:-**

In [2]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import pandas as pd

In [4]:
df=pd.read_csv('/content/insurance - insurance.csv')
df.head(5)

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [5]:
df=df.dropna()

In [6]:
ohe=OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)

In [13]:
new=ohe.fit_transform(df[['sex','smoker','region']])
new

array([[0, 1, 0, 0, 1],
       [1, 0, 0, 1, 0],
       [1, 0, 0, 1, 0],
       ...,
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 1, 1, 0, 0]], dtype=int32)

In [14]:
new_df=pd.DataFrame(new,columns=df.columns)
new_df.head(5)

ValueError: Shape of passed values is (1338, 5), indices imply (1338, 7)