#Decision Tree Model --> CART(classification and Regression tree)

- when data is numerical--> branch individual output avg. --> final output
- when data is categorical --> branch individual output (100 covid patients )--> 70 output(yes) /30 output(no)--> final output(70->yes)

- loss= -p_yes *log_yes -p_no * log_no

#Decision Tree is a supervised machine learning algorithm used for both:

- Classification (Yes/No, Pass/Fail)
- Regression (Predicting numbers)

#Tree Structure

A Decision Tree has 3 main parts:

1. Root Node

First question.


2. Branches

Possible answers.

Yes/
No

3. Leaf Node

Final prediction.

Pass/
Fail

#Advantages

✔ Easy to understand

✔ Easy to visualize

✔ Works for classification and regression

✔ No need for feature scaling

✔ Handles nonlinear relationships

#Disadvantages

❌ Can overfit easily

❌ Sensitive to small changes in data

❌ Large trees become complex

##Important Terms
#Gini Impurity

Used to find the best split.

A lower Gini value means a better split.

#Entropy

Measures disorder in data.

A lower entropy means purer groups.

#Information Gain

How much information we gain after a split.

Higher Information Gain = Better Split.

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

1. numerical data ---> decisiontreeregression

In [ ]:
df=pd.read_csv("/content/insurance - insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
lb=LabelEncoder()
df["sex"]=lb.fit_transform(df["sex"])
df["smoker"]=lb.fit_transform(df["smoker"])
df["region"]=lb.fit_transform(df["region"])
df.head()

   age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       3  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       1  21984.47061
4   32    1  28.880         0       0       1   3866.85520

In [ ]:
x=df.drop(columns="charges")
y=df["charges"]

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
dt=DecisionTreeRegressor()
dt.fit(x_train,y_train)

DecisionTreeRegressor()

In [ ]:
y_pred=dt.predict(x_test)

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.730182700870427

In [ ]:
df=pd.read_csv('/content/Social_Network_Ads - Social_Network_Ads.csv')
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
lb=LabelEncoder()
df["Gender"]=lb.fit_transform(df["Gender"])

In [ ]:
x=df.drop(columns="Purchased")
y=df["Purchased"]

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
y_pred=dt.predict(x_test)

In [ ]:
accuracy_score(y_test,y_pred)

0.8875

In [ ]:
df=pd.read_csv('/content/covid_toy - covid_toy.csv')
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
lb=LabelEncoder()
df["cough"]=lb.fit_transform(df["cough"])
df["gender"]=lb.fit_transform(df["gender"])
df["city"]=lb.fit_transform(df["city"])

In [ ]:
x=df.drop(columns="has_covid")
y=df["has_covid"]

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
dtc=DecisionTreeClassifier()
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
y_pred=dtc.predict(x_test)

In [ ]:
accuracy_score(y_test,y_pred)

0.5

In [ ]:
df=pd.read_csv('/content/Churn_Modelling - Churn_Modelling.csv')
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
df=df.drop(columns=["RowNumber","CustomerId","Surname"])
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
df['Geography']=lb.fit_transform(df['Geography'])
df['Gender']=lb.fit_transform(df['Gender'])

In [ ]:
x=df.drop(columns="Exited")
y=df["Exited"]

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
y_pred=dtc.predict(x_test)

In [ ]:
accuracy_score(y_test,y_pred)

0.7855

In [ ]:
r2_score(y_test,y_pred)

-0.3585601162851457

In [ ]:
1.what is dcision tree?
2.why it called tree model? what are root node,internel node and leaf node?
3.how does a decision tree make decision?
4.how does the model dicied the best feature for splotting?
5. what is impurity in decision trees?
6. what is gini impurity entropy?
7. why would you chose decision tree over logistic regression?
8. when should decicion tree be avoided?
9.how con you reduce overfitting in decision trees?